services:
  my-core-bot:
    image: ghcr.io/42core-team/my-core-bot:v0.0.4
    platform: linux/amd64
    volumes:
      - ..:/workspace
      - replays:/workspace/replays
    stdin_open: true

  visualizer:
    image: ghcr.io/42core-team/visualizer:v0.0.4.1
    ports:
      - 4000:80
    volumes:
      - replays:/usr/share/nginx/html/replays

volumes:
  replays:
